name: Run crysgen tests

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.12",]

    steps:
    - uses: actions/checkout@v4
    - name: Setup crysgen
      run: |
        pip install -e . -vvv
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
